* Joe's Arch Linux installation script

** Introduction
My original script meant to automate your Arch Linux installation process. The script was tested on virtual machine only at the moment.

/Note:/ while the script simplifies the whole installation process, this is not made for new users. It is meant for users that already performed *Arch Linux* installations and more or less understand what's going on. It's always best to learn Arch by yourself.

/Note:/  the script does not install too many bloatware other than some utils. You will be prompted to choose whether or not you want ~Xorg~ and other classic desktop user experience extras.

/Note:/ only *UEFI-type installation* is supported at the moment. *BIOS version* soon to come.

** How to use
First make sure you are booted in a live /Arch ISO environment/, with the familiar prompt waiting for instructions.

Secondly, you will require a working internet connection. To *try your connection* use:

#+BEGIN_SRC shell
ping -c4 archlinux.org
#+END_SRC

If this fails, refer to [[https://wiki.archlinux.org/index.php/Installation_guide#Connect_to_the_internet][the Arch Wiki installation guide]] to get an internet connection working.

Now you are ready to run the script. Run *the following commands* to begin setup and installation:

#+BEGIN_SRC shell
wget https://raw.githubusercontent.com/JozanLeClerc/joes-arch-install/master/joes-arch-install-UEFI.sh
chmod +x joes-arch-install-UEFI.sh
./joes-arch-install-UEFI.sh
#+END_SRC

** Disclaimers
While there is some basic error managements, *do not* try to break the script by inputting deliberately harmful stuff when prompted. As an *Arch Linux* installation can be complex and sensitive, it will most certainly work. This is meant to ease your life, it is not a skill test.

*Do NOT* run this on your already installed machine. It will *wipe* your current installation. It is meant to be used only in the live /Arch ISO environment/ and your intention must be to install *Arch Linux* on the system.

The script does not handle *dual boot* on a *single disk*, while you should be fine with an already installed OS on another disk thanks to ~os-prober~.  
It does not handle *multiple disk partitionning*.

** More
Don't hesitate to contact me or create a pull request in case of bugs, typos, cool suggestions...
